image: alpine

stages:
  - config
  - child

.default:
  rules:
    - if: '$CI_PROJECT_PATH == "alpine/docker-abuild" && $CI_COMMIT_BRANCH == "master"'
      changes:
        - Dockerfile.in
        - make_images.sh
        - entrypoint.sh

generate-yml:
  stage: config
  extends: .default
  script:
    - apk add --no-cache jq curl
    - ./mkyml.sh > child-pipeline.yml
  artifacts:
    paths:
      - child-pipeline.yml

child-pipeline:
  stage: child
  extends: .default
  trigger:
    include:
      - artifact: child-pipeline.yml
        job: generate-yml
